name = "puzzle_08"
description = "Advent of Code 2021 - SevenSegment"
tags = ["AoC-2021","Streams","Stream_IO","Exceptions","Command_Line"]
version = "1.0.0"
licenses = CC-BY-SA-4.0

authors = ["William J. FRANCK"]
maintainers = ["William J. FRANCK <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["puzzle_08"]

website = ["https://github.com/AdaForge/Advent_of_Code_2021"]
