name = "puzzle_06"
description = "Advent of Code 2021 - Lanternfishs"
tags = ["AoC-2021","Big_Numbers","Dynamic allocation","Command_Line"]
version = "1.0.0"
licenses = CC-BY-SA-4.0

authors = ["William J. FRANCK"]
maintainers = ["William J. FRANCK <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["puzzle_06_Pyramid","puzzle_06_Relatives"]

website = ["https://github.com/AdaForge/Advent_of_Code_2021"]
