name = "puzzle_07"
description = "Advent of Code 2021 - Crabs"
tags = ["AoC-2021","generic","Command_Line"]
version = "1.0.0"
licenses = CC-BY-SA-4.0

authors = ["William J. FRANCK"]
maintainers = ["William J. FRANCK <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["puzzle_07"]

website = ["https://github.com/AdaForge/Advent_of_Code_2021"]
