name = "puzzle_02"
description = "Advent of Code 2021 - Submarine.Navigation"
tags = ["AoC-2021","Enumeration_IO"]
version = "1.0.0"
licenses = CC-BY-SA-4.0

authors = ["William J. FRANCK"]
maintainers = ["William J. FRANCK <william@sterna.io>"]
maintainers-logins = ["captain-haddock17"]

executables = ["puzzle_02_A", "puzzle_02_B"]

website = ["https://github.com/AdaForge/Advent_of_Code_2021"]
